services:
  - type: web
    name: nostalgia
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
